"""validate token delete isseller in database

Revision ID: 84d739741c7d
Revises: a6a1817c71b7
Create Date: 2025-08-20 20:34:50.240380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d739741c7d'
down_revision: Union[str, Sequence[str], None] = 'a6a1817c71b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isSeller')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isSeller', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
