"""add param

Revision ID: c672fea724d1
Revises: a8fc5fc51c57
Create Date: 2025-09-04 17:22:42.595955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c672fea724d1'
down_revision: Union[str, Sequence[str], None] = 'a8fc5fc51c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phoneNumber', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phoneNumber')
    op.drop_column('users', 'company_name')
    # ### end Alembic commands ###
